name: Bug Report
description: File a bug report to help improve Composer user experience.
labels: ["Bug"]
body:
  - type: markdown
    attributes:
      value: |
        #### ADVISORY
        "We do not support any versions older than the current release series"

        "Please post all details in **English**."

        #### Prerequisites before submitting an issue!
        - Read the issue reporting section in the **[contributing guidelines](https://github.com/performous/composer/blob/master/.github/CONTRIBUTING.md#how-to-write-a-good-issue)**, to know how to submit a good bug report with the required information.
        - Verify that the issue is not fixed and is reproducible in the **[latest official Performous version](https://github.com/performous/composer/releases/latest).**
        - (Optional, but recommended) Verify that the issue is not fixed and is reproducible in the latest **[CI builds](https://github.com/performous/composer/actions?query=event%3Apush+is%3Acompleted+branch%3Amaster+workflow%3A%22Build+and+Release+Composer%22++)**.
        - Perform a **[search of the issue tracker (including closed ones)](https://github.com/performous/composer/issues)** to avoid posting a duplicate.
        - Make sure this is not a support request or question, both of which are better suited for either the **[discussions section](https://github.com/performous/composer/discussions)** or **[Discord - User Support channel](https://discord.gg/NS3m3ad)**.
        - Verify that the **[wiki](https://github.com/performous/composer/wiki)** did not contain a suitable solution either.

  - type: textarea
    attributes:
      label: Composer & operating system versions
      description: |
        Composer version can be found with: composer --version

        Example of preferred formatting:
        Composer: 1.2.0
        Operating system: Windows 10 Pro 21H1/2009 x64
      placeholder: |
        Composer:
        Operating system:
    validations:
      required: true

  - type: textarea
    attributes:
      label: What is the problem?
      description: Please give a clear and concise description of the problem.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Please provide reliable steps to reproduce the problem.
      placeholder: |
        1. First step
        2. Second step
        3. and so on...
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional context
      description: Add screenshots etc. (Anything that will provide more context about the problem)
    validations:
      required: false